// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(context_runtimeFFI)
import context_runtimeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_context_runtime_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_context_runtime_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureContextRuntimeInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AsyncCompilationFutureProtocol: AnyObject, Sendable {
    
    func cancel()  -> Bool
    
    func isReady()  -> Bool
    
    func pollResult()  -> CompileResultFfi?
    
}
open class AsyncCompilationFuture: AsyncCompilationFutureProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_context_runtime_fn_clone_asynccompilationfuture(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_context_runtime_fn_free_asynccompilationfuture(pointer, $0) }
    }

    

    
open func cancel() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_asynccompilationfuture_cancel(self.uniffiClonePointer(),$0
    )
})
}
    
open func isReady() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_asynccompilationfuture_is_ready(self.uniffiClonePointer(),$0
    )
})
}
    
open func pollResult() -> CompileResultFfi?  {
    return try!  FfiConverterOptionTypeCompileResultFfi.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_asynccompilationfuture_poll_result(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsyncCompilationFuture: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AsyncCompilationFuture

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AsyncCompilationFuture {
        return AsyncCompilationFuture(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AsyncCompilationFuture) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AsyncCompilationFuture {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AsyncCompilationFuture, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsyncCompilationFuture_lift(_ pointer: UnsafeMutableRawPointer) throws -> AsyncCompilationFuture {
    return try FfiConverterTypeAsyncCompilationFuture.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsyncCompilationFuture_lower(_ value: AsyncCompilationFuture) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAsyncCompilationFuture.lower(value)
}






public protocol ContextRuntimeHandleProtocol: AnyObject, Sendable {
    
    func cancelCompilation(jobId: String)  -> Bool
    
    func close(uri: String) 
    
    func compile(uri: String)  -> String
    
    func compileAsync(uri: String)  -> AsyncCompilationFuture?
    
    func getActiveJobs()  -> [String]
    
    func getDiagnostics(uri: String)  -> [DiagnosticFfi]
    
    func getDocumentSource(uri: String)  -> String?
    
    func getDocumentUris()  -> [String]
    
    func getHighlights(uri: String)  -> [HighlightFfi]
    
    func notifyDiagnosticsUpdated(uri: String, diagnostics: [DiagnosticFfi]) 
    
    func notifyError(error: RuntimeErrorFfi) 
    
    func notifyHighlightsUpdated(uri: String, highlights: [HighlightFfi]) 
    
    func `open`(uri: String, content: String)  -> Bool
    
    func setLiveCallback(callback: LiveUpdateCallback?) 
    
    func update(uri: String, start: UInt32, end: UInt32, newText: String)  -> Bool
    
}
open class ContextRuntimeHandle: ContextRuntimeHandleProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_context_runtime_fn_clone_contextruntimehandle(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_context_runtime_fn_constructor_contextruntimehandle_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_context_runtime_fn_free_contextruntimehandle(pointer, $0) }
    }

    
public static func newWithConfig(config: RuntimeConfigFfi) -> ContextRuntimeHandle  {
    return try!  FfiConverterTypeContextRuntimeHandle_lift(try! rustCall() {
    uniffi_context_runtime_fn_constructor_contextruntimehandle_new_with_config(
        FfiConverterTypeRuntimeConfigFfi_lower(config),$0
    )
})
}
    

    
open func cancelCompilation(jobId: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_cancel_compilation(self.uniffiClonePointer(),
        FfiConverterString.lower(jobId),$0
    )
})
}
    
open func close(uri: String)  {try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_close(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
}
}
    
open func compile(uri: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_compile(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
})
}
    
open func compileAsync(uri: String) -> AsyncCompilationFuture?  {
    return try!  FfiConverterOptionTypeAsyncCompilationFuture.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_compile_async(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
})
}
    
open func getActiveJobs() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_get_active_jobs(self.uniffiClonePointer(),$0
    )
})
}
    
open func getDiagnostics(uri: String) -> [DiagnosticFfi]  {
    return try!  FfiConverterSequenceTypeDiagnosticFfi.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_get_diagnostics(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
})
}
    
open func getDocumentSource(uri: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_get_document_source(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
})
}
    
open func getDocumentUris() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_get_document_uris(self.uniffiClonePointer(),$0
    )
})
}
    
open func getHighlights(uri: String) -> [HighlightFfi]  {
    return try!  FfiConverterSequenceTypeHighlightFfi.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_get_highlights(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
})
}
    
open func notifyDiagnosticsUpdated(uri: String, diagnostics: [DiagnosticFfi])  {try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_notify_diagnostics_updated(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),
        FfiConverterSequenceTypeDiagnosticFfi.lower(diagnostics),$0
    )
}
}
    
open func notifyError(error: RuntimeErrorFfi)  {try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_notify_error(self.uniffiClonePointer(),
        FfiConverterTypeRuntimeErrorFfi_lower(error),$0
    )
}
}
    
open func notifyHighlightsUpdated(uri: String, highlights: [HighlightFfi])  {try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_notify_highlights_updated(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),
        FfiConverterSequenceTypeHighlightFfi.lower(highlights),$0
    )
}
}
    
open func `open`(uri: String, content: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_open(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func setLiveCallback(callback: LiveUpdateCallback?)  {try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_set_live_callback(self.uniffiClonePointer(),
        FfiConverterOptionCallbackInterfaceLiveUpdateCallback.lower(callback),$0
    )
}
}
    
open func update(uri: String, start: UInt32, end: UInt32, newText: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_context_runtime_fn_method_contextruntimehandle_update(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),
        FfiConverterUInt32.lower(start),
        FfiConverterUInt32.lower(end),
        FfiConverterString.lower(newText),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContextRuntimeHandle: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ContextRuntimeHandle

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ContextRuntimeHandle {
        return ContextRuntimeHandle(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ContextRuntimeHandle) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ContextRuntimeHandle {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ContextRuntimeHandle, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContextRuntimeHandle_lift(_ pointer: UnsafeMutableRawPointer) throws -> ContextRuntimeHandle {
    return try FfiConverterTypeContextRuntimeHandle.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContextRuntimeHandle_lower(_ value: ContextRuntimeHandle) -> UnsafeMutableRawPointer {
    return FfiConverterTypeContextRuntimeHandle.lower(value)
}




public struct CompileRequestFfi {
    public var fileName: String
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fileName: String, content: String) {
        self.fileName = fileName
        self.content = content
    }
}

#if compiler(>=6)
extension CompileRequestFfi: Sendable {}
#endif


extension CompileRequestFfi: Equatable, Hashable {
    public static func ==(lhs: CompileRequestFfi, rhs: CompileRequestFfi) -> Bool {
        if lhs.fileName != rhs.fileName {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fileName)
        hasher.combine(content)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompileRequestFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompileRequestFfi {
        return
            try CompileRequestFfi(
                fileName: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CompileRequestFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileRequestFfi_lift(_ buf: RustBuffer) throws -> CompileRequestFfi {
    return try FfiConverterTypeCompileRequestFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileRequestFfi_lower(_ value: CompileRequestFfi) -> RustBuffer {
    return FfiConverterTypeCompileRequestFfi.lower(value)
}


public struct CompileResponseFfi {
    public var success: Bool
    public var pdfPath: String?
    public var log: String
    public var diagnostics: [DiagnosticFfi]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(success: Bool, pdfPath: String?, log: String, diagnostics: [DiagnosticFfi]) {
        self.success = success
        self.pdfPath = pdfPath
        self.log = log
        self.diagnostics = diagnostics
    }
}

#if compiler(>=6)
extension CompileResponseFfi: Sendable {}
#endif


extension CompileResponseFfi: Equatable, Hashable {
    public static func ==(lhs: CompileResponseFfi, rhs: CompileResponseFfi) -> Bool {
        if lhs.success != rhs.success {
            return false
        }
        if lhs.pdfPath != rhs.pdfPath {
            return false
        }
        if lhs.log != rhs.log {
            return false
        }
        if lhs.diagnostics != rhs.diagnostics {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(success)
        hasher.combine(pdfPath)
        hasher.combine(log)
        hasher.combine(diagnostics)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompileResponseFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompileResponseFfi {
        return
            try CompileResponseFfi(
                success: FfiConverterBool.read(from: &buf), 
                pdfPath: FfiConverterOptionString.read(from: &buf), 
                log: FfiConverterString.read(from: &buf), 
                diagnostics: FfiConverterSequenceTypeDiagnosticFfi.read(from: &buf)
        )
    }

    public static func write(_ value: CompileResponseFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.pdfPath, into: &buf)
        FfiConverterString.write(value.log, into: &buf)
        FfiConverterSequenceTypeDiagnosticFfi.write(value.diagnostics, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileResponseFfi_lift(_ buf: RustBuffer) throws -> CompileResponseFfi {
    return try FfiConverterTypeCompileResponseFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileResponseFfi_lower(_ value: CompileResponseFfi) -> RustBuffer {
    return FfiConverterTypeCompileResponseFfi.lower(value)
}


public struct CompileResultFfi {
    public var success: Bool
    public var pdfPath: String?
    public var log: String
    public var diagnostics: [DiagnosticFfi]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(success: Bool, pdfPath: String?, log: String, diagnostics: [DiagnosticFfi]) {
        self.success = success
        self.pdfPath = pdfPath
        self.log = log
        self.diagnostics = diagnostics
    }
}

#if compiler(>=6)
extension CompileResultFfi: Sendable {}
#endif


extension CompileResultFfi: Equatable, Hashable {
    public static func ==(lhs: CompileResultFfi, rhs: CompileResultFfi) -> Bool {
        if lhs.success != rhs.success {
            return false
        }
        if lhs.pdfPath != rhs.pdfPath {
            return false
        }
        if lhs.log != rhs.log {
            return false
        }
        if lhs.diagnostics != rhs.diagnostics {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(success)
        hasher.combine(pdfPath)
        hasher.combine(log)
        hasher.combine(diagnostics)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompileResultFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompileResultFfi {
        return
            try CompileResultFfi(
                success: FfiConverterBool.read(from: &buf), 
                pdfPath: FfiConverterOptionString.read(from: &buf), 
                log: FfiConverterString.read(from: &buf), 
                diagnostics: FfiConverterSequenceTypeDiagnosticFfi.read(from: &buf)
        )
    }

    public static func write(_ value: CompileResultFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.pdfPath, into: &buf)
        FfiConverterString.write(value.log, into: &buf)
        FfiConverterSequenceTypeDiagnosticFfi.write(value.diagnostics, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileResultFfi_lift(_ buf: RustBuffer) throws -> CompileResultFfi {
    return try FfiConverterTypeCompileResultFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileResultFfi_lower(_ value: CompileResultFfi) -> RustBuffer {
    return FfiConverterTypeCompileResultFfi.lower(value)
}


public struct DiagnosticFfi {
    public var start: UInt32
    public var end: UInt32
    public var severity: String
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, end: UInt32, severity: String, message: String) {
        self.start = start
        self.end = end
        self.severity = severity
        self.message = message
    }
}

#if compiler(>=6)
extension DiagnosticFfi: Sendable {}
#endif


extension DiagnosticFfi: Equatable, Hashable {
    public static func ==(lhs: DiagnosticFfi, rhs: DiagnosticFfi) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        if lhs.severity != rhs.severity {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
        hasher.combine(severity)
        hasher.combine(message)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiagnosticFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiagnosticFfi {
        return
            try DiagnosticFfi(
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf), 
                severity: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DiagnosticFfi, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
        FfiConverterString.write(value.severity, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnosticFfi_lift(_ buf: RustBuffer) throws -> DiagnosticFfi {
    return try FfiConverterTypeDiagnosticFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnosticFfi_lower(_ value: DiagnosticFfi) -> RustBuffer {
    return FfiConverterTypeDiagnosticFfi.lower(value)
}


public struct FfiRange {
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, end: UInt32) {
        self.start = start
        self.end = end
    }
}

#if compiler(>=6)
extension FfiRange: Sendable {}
#endif


extension FfiRange: Equatable, Hashable {
    public static func ==(lhs: FfiRange, rhs: FfiRange) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRange {
        return
            try FfiRange(
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRange, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRange_lift(_ buf: RustBuffer) throws -> FfiRange {
    return try FfiConverterTypeFfiRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRange_lower(_ value: FfiRange) -> RustBuffer {
    return FfiConverterTypeFfiRange.lower(value)
}


public struct HighlightFfi {
    public var range: FfiRange
    public var kind: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(range: FfiRange, kind: String) {
        self.range = range
        self.kind = kind
    }
}

#if compiler(>=6)
extension HighlightFfi: Sendable {}
#endif


extension HighlightFfi: Equatable, Hashable {
    public static func ==(lhs: HighlightFfi, rhs: HighlightFfi) -> Bool {
        if lhs.range != rhs.range {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(range)
        hasher.combine(kind)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHighlightFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HighlightFfi {
        return
            try HighlightFfi(
                range: FfiConverterTypeFfiRange.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HighlightFfi, into buf: inout [UInt8]) {
        FfiConverterTypeFfiRange.write(value.range, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightFfi_lift(_ buf: RustBuffer) throws -> HighlightFfi {
    return try FfiConverterTypeHighlightFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightFfi_lower(_ value: HighlightFfi) -> RustBuffer {
    return FfiConverterTypeHighlightFfi.lower(value)
}


public struct RuntimeConfigFfi {
    public var remote: Bool
    public var serverUrl: String?
    public var authToken: String?
    public var localExecutable: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(remote: Bool, serverUrl: String?, authToken: String?, localExecutable: String?) {
        self.remote = remote
        self.serverUrl = serverUrl
        self.authToken = authToken
        self.localExecutable = localExecutable
    }
}

#if compiler(>=6)
extension RuntimeConfigFfi: Sendable {}
#endif


extension RuntimeConfigFfi: Equatable, Hashable {
    public static func ==(lhs: RuntimeConfigFfi, rhs: RuntimeConfigFfi) -> Bool {
        if lhs.remote != rhs.remote {
            return false
        }
        if lhs.serverUrl != rhs.serverUrl {
            return false
        }
        if lhs.authToken != rhs.authToken {
            return false
        }
        if lhs.localExecutable != rhs.localExecutable {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(remote)
        hasher.combine(serverUrl)
        hasher.combine(authToken)
        hasher.combine(localExecutable)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRuntimeConfigFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RuntimeConfigFfi {
        return
            try RuntimeConfigFfi(
                remote: FfiConverterBool.read(from: &buf), 
                serverUrl: FfiConverterOptionString.read(from: &buf), 
                authToken: FfiConverterOptionString.read(from: &buf), 
                localExecutable: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: RuntimeConfigFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.remote, into: &buf)
        FfiConverterOptionString.write(value.serverUrl, into: &buf)
        FfiConverterOptionString.write(value.authToken, into: &buf)
        FfiConverterOptionString.write(value.localExecutable, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfigFfi_lift(_ buf: RustBuffer) throws -> RuntimeConfigFfi {
    return try FfiConverterTypeRuntimeConfigFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfigFfi_lower(_ value: RuntimeConfigFfi) -> RustBuffer {
    return FfiConverterTypeRuntimeConfigFfi.lower(value)
}


public struct TextRangeFfi {
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, end: UInt32) {
        self.start = start
        self.end = end
    }
}

#if compiler(>=6)
extension TextRangeFfi: Sendable {}
#endif


extension TextRangeFfi: Equatable, Hashable {
    public static func ==(lhs: TextRangeFfi, rhs: TextRangeFfi) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextRangeFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextRangeFfi {
        return
            try TextRangeFfi(
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: TextRangeFfi, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRangeFfi_lift(_ buf: RustBuffer) throws -> TextRangeFfi {
    return try FfiConverterTypeTextRangeFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRangeFfi_lower(_ value: TextRangeFfi) -> RustBuffer {
    return FfiConverterTypeTextRangeFfi.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum RuntimeErrorFfi {
    
    case documentNotFound(uri: String
    )
    case lockPoisoned
    case compilationError(details: String
    )
}


#if compiler(>=6)
extension RuntimeErrorFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRuntimeErrorFfi: FfiConverterRustBuffer {
    typealias SwiftType = RuntimeErrorFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RuntimeErrorFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .documentNotFound(uri: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .lockPoisoned
        
        case 3: return .compilationError(details: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RuntimeErrorFfi, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .documentNotFound(uri):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(uri, into: &buf)
            
        
        case .lockPoisoned:
            writeInt(&buf, Int32(2))
        
        
        case let .compilationError(details):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(details, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeErrorFfi_lift(_ buf: RustBuffer) throws -> RuntimeErrorFfi {
    return try FfiConverterTypeRuntimeErrorFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeErrorFfi_lower(_ value: RuntimeErrorFfi) -> RustBuffer {
    return FfiConverterTypeRuntimeErrorFfi.lower(value)
}


extension RuntimeErrorFfi: Equatable, Hashable {}






public protocol LiveUpdateCallback: AnyObject, Sendable {
    
    func onHighlightsUpdated(uri: String, highlights: [HighlightFfi]) 
    
    func onDiagnosticsUpdated(uri: String, diagnostics: [DiagnosticFfi]) 
    
    func onCompilationCompleted(uri: String, result: CompileResultFfi) 
    
    func onError(error: RuntimeErrorFfi) 
    
}
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceLiveUpdateCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceLiveUpdateCallback] = [UniffiVTableCallbackInterfaceLiveUpdateCallback(
        onHighlightsUpdated: { (
            uniffiHandle: UInt64,
            uri: RustBuffer,
            highlights: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceLiveUpdateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onHighlightsUpdated(
                     uri: try FfiConverterString.lift(uri),
                     highlights: try FfiConverterSequenceTypeHighlightFfi.lift(highlights)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDiagnosticsUpdated: { (
            uniffiHandle: UInt64,
            uri: RustBuffer,
            diagnostics: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceLiveUpdateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDiagnosticsUpdated(
                     uri: try FfiConverterString.lift(uri),
                     diagnostics: try FfiConverterSequenceTypeDiagnosticFfi.lift(diagnostics)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onCompilationCompleted: { (
            uniffiHandle: UInt64,
            uri: RustBuffer,
            result: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceLiveUpdateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onCompilationCompleted(
                     uri: try FfiConverterString.lift(uri),
                     result: try FfiConverterTypeCompileResultFfi_lift(result)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            error: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceLiveUpdateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     error: try FfiConverterTypeRuntimeErrorFfi_lift(error)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceLiveUpdateCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface LiveUpdateCallback: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitLiveUpdateCallback() {
    uniffi_context_runtime_fn_init_callback_vtable_liveupdatecallback(UniffiCallbackInterfaceLiveUpdateCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceLiveUpdateCallback {
    fileprivate static let handleMap = UniffiHandleMap<LiveUpdateCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceLiveUpdateCallback : FfiConverter {
    typealias SwiftType = LiveUpdateCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceLiveUpdateCallback_lift(_ handle: UInt64) throws -> LiveUpdateCallback {
    return try FfiConverterCallbackInterfaceLiveUpdateCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceLiveUpdateCallback_lower(_ v: LiveUpdateCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceLiveUpdateCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAsyncCompilationFuture: FfiConverterRustBuffer {
    typealias SwiftType = AsyncCompilationFuture?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAsyncCompilationFuture.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAsyncCompilationFuture.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCompileResultFfi: FfiConverterRustBuffer {
    typealias SwiftType = CompileResultFfi?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCompileResultFfi.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCompileResultFfi.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceLiveUpdateCallback: FfiConverterRustBuffer {
    typealias SwiftType = LiveUpdateCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceLiveUpdateCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceLiveUpdateCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiagnosticFfi: FfiConverterRustBuffer {
    typealias SwiftType = [DiagnosticFfi]

    public static func write(_ value: [DiagnosticFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiagnosticFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DiagnosticFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [DiagnosticFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiagnosticFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHighlightFfi: FfiConverterRustBuffer {
    typealias SwiftType = [HighlightFfi]

    public static func write(_ value: [HighlightFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHighlightFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HighlightFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [HighlightFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHighlightFfi.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_context_runtime_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_context_runtime_checksum_method_asynccompilationfuture_cancel() != 36856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_asynccompilationfuture_is_ready() != 17883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_asynccompilationfuture_poll_result() != 53559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_cancel_compilation() != 33834) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_close() != 33503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_compile() != 2187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_compile_async() != 17751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_get_active_jobs() != 20343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_get_diagnostics() != 12217) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_get_document_source() != 44195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_get_document_uris() != 7948) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_get_highlights() != 5593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_notify_diagnostics_updated() != 32893) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_notify_error() != 16515) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_notify_highlights_updated() != 39971) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_open() != 16795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_set_live_callback() != 56974) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_contextruntimehandle_update() != 3438) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_constructor_contextruntimehandle_new() != 1461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_constructor_contextruntimehandle_new_with_config() != 23783) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_liveupdatecallback_on_highlights_updated() != 18557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_liveupdatecallback_on_diagnostics_updated() != 28307) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_liveupdatecallback_on_compilation_completed() != 46638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_context_runtime_checksum_method_liveupdatecallback_on_error() != 57446) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitLiveUpdateCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureContextRuntimeInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all